package mcpserver

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/soggycactus/paprika-3-mcp/internal/paprika"
)

type NewServerOptions struct {
	Version  string
	Username string
	Password string
	Paprika  *paprika.Client
	Logger   *slog.Logger
}

func NewServer(opts NewServerOptions) (*Server, error) {
	paprika3, err := paprika.NewClient(opts.Username, opts.Password, opts.Version, opts.Logger)
	if err != nil {
		return nil, err
	}

	s := server.NewMCPServer("paprika-3-mcp", opts.Version, server.WithResourceCapabilities(false, false))
	return &Server{
		paprika3: paprika3,
		server:   s,
		logger:   opts.Logger,
		cache:    make(map[string]*paprika.Recipe),
	}, nil
}

type Server struct {
	paprika3 *paprika.Client
	logger   *slog.Logger
	server   *server.MCPServer

	cacheMu sync.RWMutex
	cache   map[string]*paprika.Recipe
}

func (s *Server) Start() {
	go s.updateResources()

	createRecipeTool := mcp.NewTool("create_paprika_recipe",
		mcp.WithDescription("Save new recipes generated by LLMs in the Paprika 3 app"),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.DefaultString("")),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.DefaultString("")),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.DefaultString("")),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.DefaultString("")),
	)
	updateRecipeTool := mcp.NewTool("update_paprika_recipe",
		mcp.WithDescription("Update existing recipes in the Paprika 3 app"),
		mcp.WithString("uid", mcp.Description("The UID of the recipe"), mcp.Required()),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.Required()),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.Required()),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.Required()),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.Required()),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.Required()),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.Required()),
	)
	listRecipesTool := mcp.NewTool("list_paprika_recipes",
		mcp.WithDescription("List recipes saved in the Paprika 3 app (name, uid, and categories only - use get_paprika_recipe for full details like ingredients and directions). Useful for browsing what's available before meal planning or building a grocery list."),
		mcp.WithString("query", mcp.Description("Optional case-insensitive filter - only recipes whose name or categories contain this text are returned. Omit to list everything.")),
	)
	getRecipeTool := mcp.NewTool("get_paprika_recipe",
		mcp.WithDescription("Get the full details of a single recipe from the Paprika 3 app, including ingredients, directions, servings, and prep/cook time. Use list_paprika_recipes first to find the uid, or pass name to look it up by exact or partial name match."),
		mcp.WithString("uid", mcp.Description("The UID of the recipe, as returned by list_paprika_recipes")),
		mcp.WithString("name", mcp.Description("The name of the recipe to look up, if the uid is not known. Matches case-insensitively; must match exactly one recipe.")),
	)
	s.server.AddTools(server.ServerTool{
		Tool:    createRecipeTool,
		Handler: s.createRecipe,
	}, server.ServerTool{
		Tool:    updateRecipeTool,
		Handler: s.updateRecipe,
	}, server.ServerTool{
		Tool:    listRecipesTool,
		Handler: s.listRecipes,
	}, server.ServerTool{
		Tool:    getRecipeTool,
		Handler: s.getRecipe,
	})

	if err := server.ServeStdio(s.server); err != nil {
		s.logger.Error("Server error", "err", err)
	}
}

func (s *Server) updateResources() {
	s.addResources()

	ticker := time.NewTicker(1 * time.Minute)
	for range ticker.C {
		s.addResources()
	}
}

func (s *Server) addResources() {
	s.logger.Info("Updating recipe resources")
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	// List all recipes to expose them as resources
	recipes, err := s.paprika3.ListRecipes(ctx)
	if err != nil {
		s.logger.Error("failed to list paprika recipes", "err", err)
		return
	}

	if len(recipes.Result) >= 10 {
		s.logger.Info("adding recipes resources concurrently")
		s.addResourcesConcurrently(recipes)
		return
	}

	for _, r := range recipes.Result {
		if err := s.addRecipeResource(r.UID); err != nil {
			s.logger.Error("failed to add recipe as MCP resource", "err", err)
		}
	}
}

func (s *Server) addRecipeResource(uid string) error {
	start := time.Now()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.GetRecipe(ctx, uid)
	if err != nil {
		return err
	}

	if recipe.InTrash {
		s.cacheMu.Lock()
		delete(s.cache, recipe.UID)
		s.cacheMu.Unlock()
		return nil
	}

	s.cacheMu.Lock()
	s.cache[recipe.UID] = recipe
	s.cacheMu.Unlock()

	resourceContents := mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}

	s.server.AddResource(mcp.NewResource(fmt.Sprintf("paprika://recipes/%s", recipe.UID), recipe.Name, mcp.WithResourceDescription(recipe.ResourceDescription()), mcp.WithMIMEType("text/markdown")), func(ctx context.Context, request mcp.ReadResourceRequest) ([]mcp.ResourceContents, error) {
		return []mcp.ResourceContents{resourceContents}, nil
	})

	duration := time.Since(start)
	s.logger.Info("Added resource", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return nil
}

func (s *Server) addResourcesConcurrently(recipes *paprika.RecipeList) {
	buffer := make(chan struct{}, 10)

	for _, r := range recipes.Result {
		go func() (err error) {
			buffer <- struct{}{}
			defer func() {
				<-buffer
			}()

			defer func(err error) {
				if err != nil {
					s.logger.Error("failed to add recipe as MCP resource", "err", err)
				}
			}(err)

			return s.addRecipeResource(r.UID)
		}()
	}
}

func (s *Server) createRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	name, ok := req.Params.Arguments["name"].(string)
	if !ok || len(name) == 0 {
		return nil, errors.New("name is required")
	}
	ingredients, ok := req.Params.Arguments["ingredients"].(string)
	if !ok || len(ingredients) == 0 {
		return nil, errors.New("ingredients are required")
	}
	directions, ok := req.Params.Arguments["directions"].(string)
	if !ok || len(directions) == 0 {
		return nil, errors.New("directions are required")
	}
	servings := req.Params.Arguments["servings"].(string)
	prepTime := req.Params.Arguments["prep_time"].(string)
	cookTime := req.Params.Arguments["cook_time"].(string)
	description := req.Params.Arguments["description"].(string)
	notes := req.Params.Arguments["notes"].(string)
	difficulty := req.Params.Arguments["difficulty"].(string)

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.SaveRecipe(ctx, paprika.Recipe{
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
	})
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Created recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}

func (s *Server) updateRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	uid, ok := req.Params.Arguments["uid"].(string)
	if !ok || len(uid) == 0 {
		return nil, errors.New("uid is required")
	}
	name, ok := req.Params.Arguments["name"].(string)
	if !ok || len(name) == 0 {
		return nil, errors.New("name is required")
	}
	ingredients, ok := req.Params.Arguments["ingredients"].(string)
	if !ok || len(ingredients) == 0 {
		return nil, errors.New("ingredients are required")
	}
	directions, ok := req.Params.Arguments["directions"].(string)
	if !ok || len(directions) == 0 {
		return nil, errors.New("directions are required")
	}
	description, ok := req.Params.Arguments["description"].(string)
	if !ok {
		return nil, errors.New("description is required")
	}
	servings, ok := req.Params.Arguments["servings"].(string)
	if !ok {
		return nil, errors.New("servings is required")
	}
	prepTime, ok := req.Params.Arguments["prep_time"].(string)
	if !ok {
		return nil, errors.New("prepTime is required")
	}
	cookTime, ok := req.Params.Arguments["cook_time"].(string)
	if !ok {
		return nil, errors.New("cookTime is required")
	}
	notes, ok := req.Params.Arguments["notes"].(string)
	if !ok {
		return nil, errors.New("notes is required")
	}
	difficulty, ok := req.Params.Arguments["difficulty"].(string)
	if !ok {
		return nil, errors.New("difficulty is required")
	}

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.SaveRecipe(ctx, paprika.Recipe{
		UID:         uid,
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
	})
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Updated recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}

func (s *Server) listRecipes(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	query := strings.ToLower(strings.TrimSpace(fmt.Sprintf("%v", req.Params.Arguments["query"])))
	if query == "<nil>" {
		query = ""
	}

	s.cacheMu.RLock()
	recipes := make([]*paprika.Recipe, 0, len(s.cache))
	for _, r := range s.cache {
		recipes = append(recipes, r)
	}
	s.cacheMu.RUnlock()

	sort.Slice(recipes, func(i, j int) bool {
		return strings.ToLower(recipes[i].Name) < strings.ToLower(recipes[j].Name)
	})

	var sb strings.Builder
	count := 0
	for _, r := range recipes {
		if query != "" && !strings.Contains(strings.ToLower(r.Name), query) && !strings.Contains(strings.ToLower(strings.Join(r.Categories, " ")), query) {
			continue
		}
		count++
		sb.WriteString(fmt.Sprintf("- **%s** (uid: %s)", r.Name, r.UID))
		if len(r.Categories) > 0 {
			sb.WriteString(fmt.Sprintf(" - categories: %s", strings.Join(r.Categories, ", ")))
		}
		if macros := r.Macros(); macros != "" {
			sb.WriteString(fmt.Sprintf(" - %s", macros))
		}
		sb.WriteString("\n")
	}

	if count == 0 {
		return mcp.NewToolResultText("No recipes found matching that query."), nil
	}

	return mcp.NewToolResultText(fmt.Sprintf("Found %d recipe(s):\n\n%s", count, sb.String())), nil
}

func (s *Server) getRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	uid, _ := req.Params.Arguments["uid"].(string)
	name, _ := req.Params.Arguments["name"].(string)

	if uid == "" && name == "" {
		return nil, errors.New("either uid or name is required")
	}

	if uid == "" {
		s.cacheMu.RLock()
		var matches []*paprika.Recipe
		for _, r := range s.cache {
			if strings.EqualFold(r.Name, name) || strings.Contains(strings.ToLower(r.Name), strings.ToLower(name)) {
				matches = append(matches, r)
			}
		}
		s.cacheMu.RUnlock()

		if len(matches) == 0 {
			return mcp.NewToolResultText(fmt.Sprintf("No recipe found matching name %q. Try list_paprika_recipes to see available recipes.", name)), nil
		}
		if len(matches) > 1 {
			var sb strings.Builder
			for _, r := range matches {
				sb.WriteString(fmt.Sprintf("- **%s** (uid: %s)\n", r.Name, r.UID))
			}
			return mcp.NewToolResultText(fmt.Sprintf("Multiple recipes match %q, please retry with a specific uid:\n\n%s", name, sb.String())), nil
		}
		uid = matches[0].UID
	}

	start := time.Now()
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.GetRecipe(ctx, uid)
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Fetched recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}
